apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-apps-cloud-diplomats
  namespace: argocd

  # Add this finalizer ONLY if you want these to cascade delete (A cascade delete, deletes both the app and its resources, rather than only the app.)
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io
  
spec:
  project: default

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground

    # automated:
    #   prune: true
    #   selfHeal: true
      
  source:
    repoURL: https://github.com/Jojoooo1/argo-deploy-gke-applications.git
    targetRevision: main
    path: argo-apps/overlays/dev
    plugin:
      name: envsubst
      env:
        - name: ENV
          value: dev

        - name: DNS_ENV
          value: '-dev'

        - name: DNS_DOMAIN
          value: '<your-domain.com>'
          
        - name: PROJECT
          value: "<your-gcp-dev-service-id>"

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
